[default]
cli_colors = true
port = 8000
# Generate secret_key with `openssl rand -base64 64`
secret_key = "REPLACE_WITH_YOUR_OWN_SECRET_KEY"

[default.oauth.github]
provider = "GitHub"
client_id = "REPLACE_WITH_YOUR_OWN_CLIENT_ID"
# DO NOT COMMIT OR PUBLISH THIS SECRET
client_secret = "REPLACE_WITH_YOUR_OWN_CLIENT_SECRET"
redirect_uri = "http://localhost:8000/auth/github"
